# Generated by Django 5.2.1 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='balance',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
