# Generated by Django 5.2.1 on 2025-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_remove_telegramuser_balance_alter_telegramuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
