# Generated by Django 5.2.1 on 2025-05-16 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0005_gamesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='language',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
