# Generated by Django 5.2.1 on 2025-05-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0006_remove_telegramuser_language_telegramuser_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='my.telegramuser'),
        ),
    ]
