# Generated by Django 5.2.1 on 2025-05-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0008_gameroom_playerinroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='my.telegramuser'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerinroom',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined', to='my.telegramuser'),
        ),
    ]
