# Generated by Django 5.2.1 on 2025-05-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0009_alter_gameroom_creator_alter_gamesession_bet_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_games', to='my.telegramuser'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
