# Generated by Django 5.2.1 on 2025-05-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0010_remove_gameroom_is_active_gameroom_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='guest',
        ),
    ]
