# Generated by Django 5.2.1 on 2025-05-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0011_remove_gameroom_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='playerinroom',
            name='player',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='bet_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my.telegramuser'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='GameRoom',
        ),
        migrations.DeleteModel(
            name='PlayerInRoom',
        ),
    ]
